apiVersion: apps/v1
kind: Deployment
metadata:
  name: saiguda
  labels:
    app: saiguda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saiguda
  template:
    metadata:
      labels:
        app: saiguda
    spec:
      containers:
      - name: saiguda
        image: guda654/democicd:1
        ports:
        - containerPort: 8080
